-- SQL 고득점 KIT

-- GROUP BY 1번 문제
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) FROM ANIMAL_INS GROUP BY ANIMAL_TYPE ORDER BY NAME DESC;
-- GROUP BY 2번 문제
SELECT NAME, COUNT(NAME) FROM ANIMAL_INS GROUP BY NAME HAVING COUNT(NAME) >= 2 ORDER BY NAME ASC;
-- GROUP BY 3번 문제
SELECT HOUR(DATETIME), COUNT(DATETIME) FROM ANIMAL_OUTS WHERE 9 <= HOUR(DATETIME) AND HOUR(DATETIME) <= 19 GROUP BY HOUR(DATETIME) ORDER BY HOUR(DATETIME);
-- GROUP BY 4번 문제
