-- SQL 고득점 KIT

-- SUM, MAX, MIN 1번 문제
SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME DESC LIMIT 1;
-- SUM, MAX, MIN 2번 문제
SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME ASC LIMIT 1;
-- SUM, MAX, MIN 3번 문제
SELECT COUNT(*) FROM ANIMAL_INS;
-- SUM, MAX, MIN 4번 문제
SELECT COUNT(DISTINCT NAME) FROM ANIMAL_INS;