-- SQL 고득점 KIT

-- STRING, DATE 1번 문제
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE FROM ANIMAL_INS WHERE NAME IN ('Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty');
-- STRING, DATE 2번 문제
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE ANIMAL_TYPE = 'Dog' AND NAME LIKE '%EL%' ORDER BY NAME;
-- STRING, DATE 3번 문제
SELECT ANIMAL_ID, NAME, IF(SEX_UPON_INTAKE LIKE 'Neutered%' OR SEX_UPON_INTAKE LIKE 'Spayed%', 'O', 'X') FROM ANIMAL_INS ORDER BY ANIMAL_ID;
-- STRING, DATE 4번 문제
SELECT A.ANIMAL_ID, A.NAME FROM ANIMAL_OUTS A JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID ORDER BY (B.DATETIME - A.DATETIME) ASC LIMIT 2;
-- STRING, DATE 5번 문제
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d') FROM ANIMAL_INS ORDER BY ANIMAL_ID;