-- SQL 고득점 KIT

-- SELECT 1번 문제
SELECT * FROM ANIMAL_INS ORDER BY ANIMAL_ID;
-- SELECT 2번 문제
SELECT NAME, DATETIME FROM ANIMAL_INS ORDER BY ANIMAL_ID DESC;
-- SELECT 3번 문제
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION = "Sick";
-- SELECT 4번 문제
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION != 'Aged';
-- SELECT 5번 문제
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS ORDER BY ANIMAL_ID;
-- SELECT 6번 문제
SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS ORDER BY NAME, DATETIME DESC;
-- SELECT 7번 문제
SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME ASC LIMIT 1;